name: Documentation

on:
  push:
    paths:
      - doc/**
      - .github/workflows/docs.yml
  workflow_dispatch: ~

env:
  SOURCE_DIR: ${{github.workspace}}
  BUILD_DIR: ${{github.workspace}}/build
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/.vcpkg-binary-cache
  QT_VERSION: 6.10.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #######################
      # SETUP
      #######################
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores
      - name: Set CMake Parallel level
        run: |
          echo "CMAKE_BUILD_PARALLEL_LEVEL=${{ steps.cpu-cores.outputs.count }}" >> ${GITHUB_ENV}
      - uses: actions/checkout@v4
        # Needed to grab 3rd party licenses.
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git .vcpkg
          cd .vcpkg && ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=${{github.workspace}}/.vcpkg" >> "$GITHUB_ENV"
      - name: Create vcpkg binary cache
        run: mkdir -p "${VCPKG_DEFAULT_BINARY_CACHE}"
      - name: Restore vcpkg binary cache
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-vcpkg-binary-cache-${{ hashFiles('vcpkg*.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-binary-cache-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Cache web ui deps
        uses: actions/cache@v4
        with:
          path: ${{github.workspace}}/mobile_sacn_webui/node_modules
          key: ${{runner.os}}-webui-${{hashfiles('**/package-lock.json')}}
          restore-keys: |
            ${{runner.os}}-webui-
      #######################
      # BUILD
      #######################
      - name: Configure CMake
        shell: bash
        run: >
          cmake 
          -S "${SOURCE_DIR}"
          -B "${BUILD_DIR}"
          --preset=doc
      - name: Build
        shell: bash
        run: cmake --build "${BUILD_DIR}" --target mobile_sacn_doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BUILD_DIR }}/doc/html
          cname: docs.mobilesacn.dankeenan.org
