name: GitHub Pages
on:
  workflow_dispatch: ~
  release:
    types:
      - created
      - edited
      - deleted
      - published
      - unpublished

jobs:
  run:
    uses: ${{ github.repository }}/.github/workflows/gh-pages.yml@pages
